name: example
description: A package to make Unit Test code more readable.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  test: ^1.19.2
  mocktail: ^0.2.0
  shouldly: ^0.2.4
  given_when_then_unit_test:
    path: ../

dev_dependencies:
