name: given_when_then_unit_test
description: A package to make Unit Test code more readable and well documented.
version: 0.1.0
homepage: https://github.com/AndrewPiterov/given_when_then_unit_test

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  test: ^1.16.0
  test_api: ^0.4.2

dev_dependencies:
  lint: ^1.8.2
  mocktail: ^0.3.0
  shouldly: ^0.5.0+1