name: given_when_then_unit_test
description: A package to make Unit Test code more readable and well documented.
version: 0.2.1
homepage: https://github.com/AndrewPiterov/given_when_then_unit_test

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  meta: ^1.9.1
  test: ^1.24.1 # do not upgrade

dev_dependencies:
  lint: ^2.1.2
  mocktail: ^0.3.0
  shouldly: ^0.5.0+1